.Dd July 29, 2025
.Dt MCSERVER 1
.Os
.Sh NAME
.Nm mcserver
.Nd manage Minecraft Java Edition server instances
.Sh SYNOPSIS
.Nm mcserver
.Op Fl version Ar version
.Op Fl world Ar name
.Op Fl jvm Ar path
.Op Fl noupdate
.Op Fl nocache
.Cm launch
.Ar ...
.Nm mcserver
.Op Fl version Ar version
.Op Fl noupdate
.Op Fl nocache
.Cm install
.Nm mcserver
.Fl help
.Sh DESCRIPTION
With
.Nm
you can install, launch or show the latest version of minecraft vanilla servers.
.Pp
.Sh SEE ALSO
.Xr java 1 .
.Sh AUTHORS
Written by
.An Valentin Debon Aq Mt valentin.debon@heylelos.org .
