.Dd July 29, 2025
.Dt MCSERVER 1
.Os
.Sh NAME
.Nm mcserver
.Nd manage Minecraft Java Edition server instances
.Sh SYNOPSIS
.Nm mcserver
.Op Fl snapshot Ar version
.Op Fl release Ar version
.Op Fl beta Ar version
.Op Fl alpha Ar version
.Op Fl manifest-url Ar link
.Op Fl jvm Ar path
.Op Fl world Ar path
.Op Fl nocache
.Cm install|launch|version
.Nm mcserver
.Fl help
.Sh DESCRIPTION
With
.Nm
you can install, launch or show the latest version of minecraft vanilla servers.
.Pp
.Sh SEE ALSO
.Xr java 1 .
.Sh AUTHORS
Written by
.An Valentin Debon Aq Mt valentin.debon@heylelos.org .
